#include "uv_exporter.hpp"

#include "accessor_reader.hpp"
#include "format.hpp"

#include <algorithm>
#include <sstream>

namespace glb_unwrapper {
namespace {

bool mesh_matches(const Mesh& mesh, size_t index, const std::string& filter) {
    if (filter.empty()) {
        return true;
    }
    if (mesh.name == filter) {
        return true;
    }
    try {
        return static_cast<size_t>(std::stoul(filter)) == index;
    } catch (...) {
        return false;
    }
}

} // namespace

std::string export_uv_svg(const GlbData& glb, const Model& model, const ExportOptions& options) {
    const double usable_width = std::max(1, options.width - 2 * options.margin);
    const double usable_height = std::max(1, options.height - 2 * options.margin);
    size_t triangle_count = 0;

    std::ostringstream svg;
    svg << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    svg << "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"" << options.width
        << "px\" height=\"" << options.height << "px\" viewBox=\"0 0 "
        << options.width << " " << options.height << "\">\n";
    svg << "  <metadata>Generated by glb_unwrapper. UV coordinates are normalized glTF TEXCOORD_0 space.</metadata>\n";
    svg << "  <rect x=\"0\" y=\"0\" width=\"" << options.width << "\" height=\""
        << options.height << "\" fill=\"white\"/>\n";

    for (size_t mesh_index = 0; mesh_index < model.meshes.size(); ++mesh_index) {
        const Mesh& mesh = model.meshes[mesh_index];
        if (!mesh_matches(mesh, mesh_index, options.mesh_filter)) {
            continue;
        }

        svg << "  <g id=\"mesh-" << mesh_index << "\" data-name=\"" << xml_escape(mesh.name) << "\">\n";
        for (size_t primitive_index = 0; primitive_index < mesh.primitives.size(); ++primitive_index) {
            if (options.primitive_filter >= 0 && options.primitive_filter != static_cast<int>(primitive_index)) {
                continue;
            }
            const Primitive& primitive = mesh.primitives[primitive_index];
            if (primitive.uv_accessor < 0) {
                svg << "    <!-- primitive " << primitive_index << " skipped: no TEXCOORD_0 -->\n";
                continue;
            }
            if (primitive.mode != 4) {
                svg << "    <!-- primitive " << primitive_index << " skipped: only TRIANGLES mode is supported -->\n";
                continue;
            }

            const auto uvs = read_vec2_accessor(glb, model, primitive.uv_accessor);
            std::vector<uint32_t> indices;
            if (primitive.index_accessor >= 0) {
                indices = read_index_accessor(glb, model, primitive.index_accessor);
            } else {
                indices = implicit_indices(uvs.size());
            }

            svg << "    <g id=\"mesh-" << mesh_index << "-primitive-" << primitive_index << "\"";
            svg << " fill=\"" << xml_escape(options.fill) << "\" stroke=\"" << xml_escape(options.stroke)
                << "\" stroke-width=\"1\" vector-effect=\"non-scaling-stroke\">\n";

            for (size_t i = 0; i + 2 < indices.size(); i += 3) {
                const uint32_t a = indices[i];
                const uint32_t b = indices[i + 1];
                const uint32_t c = indices[i + 2];
                if (a >= uvs.size() || b >= uvs.size() || c >= uvs.size()) {
                    continue;
                }
                const Vec2 tri[3] = {uvs[a], uvs[b], uvs[c]};
                svg << "      <polygon points=\"";
                for (const Vec2& uv : tri) {
                    const double x = options.margin + uv.u * usable_width;
                    const double v = options.flip_v ? (1.0 - uv.v) : uv.v;
                    const double y = options.margin + v * usable_height;
                    svg << format_number(x) << "," << format_number(y) << " ";
                }
                svg << "\"/>\n";
                ++triangle_count;
            }

            svg << "    </g>\n";
        }
        svg << "  </g>\n";
    }

    svg << "  <metadata>triangles=" << triangle_count << "</metadata>\n";
    svg << "</svg>\n";
    return svg.str();
}

} // namespace glb_unwrapper
